apiVersion: apps/v2
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: user19skccacr.azurecr.io/order:v2
          ports:
            - containerPort: 8080
          env:
            - name: STATUS
              valueFrom:
                configMapKeyRef:
                  name: orderst
                  key: status
          feign:
            hystrix:
              enabled: true
              
          hystrix:
            command:
              default:
                execution.isolation.thread.timeoutInMilliseconds: 500